name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.2"
        with:
          USERNAME: 'SohamR' # Hashnode Username
          COUNT: 4 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://srummanf.hashnode.dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}